# run: conda env create --file environment.yml
name: nasa-local
channels:
  - conda-forge
dependencies:
- python>=3.9
- matplotlib
- earthaccess
- jupyterlab
- cartopy
- pydap
- pip
- pip:
  - netCDF4
  - xarray
