# run: conda env create --file environment.yml

name: nasa-tutorials
channels:
  - conda-forge
dependencies:
- python>=3.9
- dask
- matplotlib
- earthaccess
- cartopy
- pydap
- pip
#- pip:
#  - netCDF4
#  - xarray
